### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Ahmadtareq63** [valeryan/vscode-phpsab#1]
- Issue Type: `Bug`
- Extension Name: `vscode-phpsab`
- Extension Version: `0.0.2`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.35.1`
```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 1364,
		"activateCallTime": 2,
		"activateResolvedTime": 4,
		"activationEvent": "onLanguage:php"
	},
	"runtimeErrors": [
		{
			"name": "TypeError [ERR_INVALID_ARG_VALUE]",
			"message": "The argument 'file' cannot be empty. Received ''"
		}
	]
}
```
:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by valeryan** [comment]
I don't use windows but I can get the os setup somewhere. However, I am not really sure what you are trying to tell me here. Maybe some context on what you were doing when this occurred or maybe some steps to reproduce.

**Comment by Ahmadtareq63** [comment]
> I don't use windows but I can get the os setup somewhere. However, I am not really sure what you are trying to tell me here. Maybe some context on what you were doing when this occurred or maybe some steps to reproduce.

thank you for replying but I have reinstalled the software and it's working smoothly
