### ISSUE TITLE
Fixing and Sniffing don't work with global install of phpcs

### ISSUE THREAD

**Issue by aka-tpayne** [valeryan/vscode-phpsab#10]
- Version: 0.0.4
- OS: MacOS Mojave 10.14.6
- VSC: 1.40.0

These errors show up whenever I open or try and save a file.

`ERR spawn /Users/<redacted>/Code/work/<redacted> EACCES: Error: spawn /Users/<redacted>/Code/work/<redacted> EACCES
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)`

`[Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:5:192)	at process.emit (events.js:200:13)`

**Comment by valeryan** [comment]
I dug my MacBook out and set up vscode with php-sab and it is running without issue for me. Also, most of my team runs MacBooks and they use this software daily. It could be some kind of permission issue. It could also be coming from some other extension interfering with this one. 

I would try disabling all extensions and just running php-sab to isolate the issue. 
Maybe send me more information about your setup like how you have phpcs installed and you .phpcs.xml file, etc..

**Comment by aka-tpayne** [comment]
I actually figured this out. I was attempting to rely on the extension finding phpcbf/phpcs on it's own (I have it installed through composer), but it isn't working for me.

I plugged in actual paths and everything seems to be working fine

**Comment by valeryan** [comment]
The extension should auto-detect the location of phpcs and it disables itself if it can't find it. when you say you have it installed through composer ( the extension requires it to be installed through composer) do you mean you have it installed globally? The extension should be able to find both a global install of phpcs and a local project copy of phpcs. 

Let me know so I can troubleshoot. thanks.

**Comment by ntwb** [comment]
Just happened upon this myself, tried running "PHPCBF Fix this file"

> `command fixer.fix not found`

I've PHPCS installed globally

```shell
❯ which phpcbf
/Users/netweb/.composer/vendor/bin/phpcbf
~/Code/tmp/wordpress-develop master*
❯ which phpcs
/Users/netweb/.composer/vendor/bin/phpcs
```

When I try and define `phpsab.executablePath` in `settings.json` VS Code shows "Unknown Configuration Setting`

> `"phpsab.executablePath": "/Users/netweb/.composer/vendor/bin/phpcbf",`

It has no issue with the `"phpsab.debug": true,` setting, ahh, that setting is no longer, there are two new settings, `phpsab.executablePathCBF` & `phpsab.executablePathCS`

> https://github.com/valeryan/vscode-phpsab/blob/master/src/configuration.ts#L30-L31

----

Ok, the above was using multiple git repos in a workspace

Using a single repo, worked fine, well PHPCBF worked as expected, unexpected was NOT seeing the PHPCS issues in the "Problems" tab in VS Code, I found this extension by way of [this comment](https://github.com/wongjn/vscode-php-sniffer/issues/5#issuecomment-504860669) and had hoped I'd get multi-repo workspace support using this extension, alas a few more tweaks and fixes sound like they are required to get all the multi-repos in a workspace sorted...

**Comment by valeryan** [comment]
@ntwb I am looking at the global install problem. I am going to probably rework the global resolver to do more of a test if phpcs is available and then use it. Right now it's looking in your path for an entry for phpcs and phpcbf.

Thanks for pointing out that my documentation is outdated. I will go through that and fix it. 

Some basic multi workspace support works but I need to rework the whole setting system for full multi workspace support. Basically the settings need to be an array of settings by workspace instead of an entity with single properties. If you want to look at how to get some basic setup take a look at issue #5

**Comment by valeryan** [comment]
@ntwb I implemented multi-workspace support. I still have not found a better way to handle auto-detecting global installs but you can configure phpcs/cbf per workspace folder now so it's easy to specify a global path in the config for all projects or do it per workspace root.
