### ISSUE TITLE
PHPCBF - Error

### ISSUE THREAD

**Issue by olliescase** [valeryan/vscode-phpsab#101]
Maybe someone could help me, as I'm not sure if this is a bug with the extension or (more likely) a configuration issue my end.

Here is my debug log:
```
FIXER COMMAND: /Users/name/Documents/path/to/project/vendor/bin/phpcbf -q --standard=PSR12 --stdin-path=/Users/name/Documents/path/to/project/app/Mail/Invite.php -
["ERROR" - 21:47:59] 
```

The thing that confuses me about this, is that if I take the file and do: 
```sh
cat {file} | {command}
```
Where the file is taken from the command, and the command is copied from the log's output.

.... it works!

So there is something, I can only assume, about what the extension is expecting that causes an error. Or maybe there is something stranger going on under the hood. Either way, any suggestions would be greatly appreciated.

**Comment by stormrockwell** [comment]
@olliescase I would suggest running the fixer command that it is showing. If that doesn't work, it would be related to your project.
```
/Users/name/Documents/path/to/project/vendor/bin/phpcbf -q --standard=PSR12 --stdin-path=/Users/name/Documents/path/to/project/app/Mail/Invite.php 
```

**Comment by valeryan** [comment]
Closing for no response. Feel free to reopen if you still need help.
