### ISSUE TITLE
Integrating PHPCompatibility

### ISSUE THREAD

**Issue by markhowellsmead** [valeryan/vscode-phpsab#103]
Is it possible to integrate https://github.com/PHPCompatibility/PHPCompatibility with vscode-phpsab?

**Comment by seebeen** [comment]
Hello, this extension works with any rulesets you define in your phpcs.xml file or in the extension settings.

If you want to see a fully configured phpcs.xml file with codesniffer look at this repo [Serbian Addons for WooCommerce](/oblakstudio/serbian-addons-for-woocommerce)
