### ISSUE TITLE
Continuing development

### ISSUE THREAD

**Issue by seebeen** [valeryan/vscode-phpsab#106]
Hello,

I'm interested in taking over the development of this extension as a maintainer.

**Comment by valeryan** [comment]
Hello @seebeen, I can talk about adding you as a collaborator. If you want to help the #97 PR is needing to be tested and evaluated so that it can be released. It has a few fixes in it that users of this extension would like. Getting that across the finish line would be a huge win for users.

**Comment by seebeen** [comment]
Sounds like a plan 💪

Feel free to add ke as a collaborator. I'll get the ball rolling.
