### ISSUE TITLE
Sniffer for other file extensions

### ISSUE THREAD

**Issue by farhadsakhaei** [valeryan/vscode-phpsab#109]
Hi,
How can I enable sniffer for other file extensions?
like CSS and JS files?

Thank you

**Comment by valeryan** [comment]
Do your CSS and JS files have PHP in them? I don't think phpcs or phpcbf has any concept of scanning non-PHP files.

**Comment by farhadsakhaei** [comment]
@valeryan 
Yes, They do
Some sniffers perform CSS , JS and other files analysis

**Comment by valeryan** [comment]
Do you have a document source for what you are talking about? I don't see anything in the documentation for PHPcs doing anything for css or js. 

I feel like you may be confused about what this extension does. It's not a general sniffer it's a wrapper for phpcs and phpcbf

**Comment by farhadsakhaei** [comment]
Yes, I am doing this everyday, actually I found another extension that it do that
Actually WordPress coding standard do this too for CSS files and JS files too

**Comment by valeryan** [comment]
I can look into it but ultimately this is a php tool and the concept of using it for css or js is weird to me and I think it would be better to use something specialized in those file types like prettier and eslint.

**Comment by farhadsakhaei** [comment]
Some projects have their own standards for any file type
So they apply such standards, like WordPress

**Comment by valeryan** [comment]
Yeah, but PHPcs does not lint the files it just passes the standards definitions to another tool such as csslint. https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-path-to-csslint

That will require some development of new configuration, detection and tooling to support. If one of the other maintainers wants to pick up and support this it might get added. Currently I am not looking to do more than maintain this extension with bug or security fixes.

**Comment by farhadsakhaei** [comment]
@valeryan 
BTW, Thank you for your development
I currently resolved that with the extension:
https://marketplace.visualstudio.com/items?itemName=wongjn.php-sniffer

phpSniffer.extraFiles: [Glob patterns](https://code.visualstudio.com/api/references/vscode-api#GlobPattern) of extra files to match that this extension should run on. Useful for standards that don't just validate PHP files. This extension will always run on PHP files — be sure to have your files.associations setting correctly setup for PHP files.

**Comment by jonathanbossenger** [comment]
@valeryan just adding my 2c here, I don't think this tool should include support for other files, when the WordPress project already has the [@wordpress/scripts package](https://www.npmjs.com/package/@wordpress/scripts) that can be used to lint JS and CSS code and can be configured to auto-format on save ([see this example project](https://github.com/ryanwelcher/wordpress-project-template)).

I'm of the opinion that the beauty of PHP Sniffer & Beautifier is that it does one thing, allow phpcs and phpcbf to be configured to run inside VSCode, and it does that one thing well.

**Comment by jonathanbossenger** [comment]
@valeryan it's worth noting that PHPCS has deprecated and will eventually drop support for any JS and CSS sniffs.

Relevant links

- https://github.com/squizlabs/PHP_CodeSniffer/issues/2448
- https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/276
- https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/188

Therefore it's probably not worth adding support for something that will not be supported in newer PHPCS versions.

**Comment by valeryan** [comment]
@jonathanbossenger thanks for researching that for us. Given that the feature is on the way out/gone I am closing this.
