### ISSUE TITLE
Formatting selection doesn't work

### ISSUE THREAD

**Issue by emil-nasso** [valeryan/vscode-phpsab#11]
If I select some part of a php-document and run a format on that selection I get an error message.

![https://dl.dropboxusercontent.com/s%2Fud2wxp72hls84oo%2FMonosnap%25202019-12-19%252014-45-06.png](https://dl.dropboxusercontent.com/s%2Fud2wxp72hls84oo%2FMonosnap%25202019-12-19%252014-45-06.png)

![https://dl.dropboxusercontent.com/s%2Fwe3zt7wkwgdd0qs%2Ftest.php%2520%2520api%25202019-12-19%252014-46-14.png](https://dl.dropboxusercontent.com/s%2Fwe3zt7wkwgdd0qs%2Ftest.php%2520%2520api%25202019-12-19%252014-46-14.png)

Is this expected or an error? Is there any way to get partial formatting using this plugin? :)

Debug is checked but no output is shown in the debug console:

![https://dl.dropboxusercontent.com/s%2Fllxpx1eq3ktjxlk%2FSettings%2520%2520api%25202019-12-19%252014-48-56.png](https://dl.dropboxusercontent.com/s%2Fllxpx1eq3ktjxlk%2FSettings%2520%2520api%25202019-12-19%252014-48-56.png)

**Comment by valeryan** [comment]
This extension does not implement a by selection formatter.

**Comment by emil-nasso** [comment]
@valeryan Ok. Is it possible to implement or is it a limitation with phpcs?

**Comment by valeryan** [comment]
I am sure it's possible. I am not sure when I will have the time to look into it.

**Comment by valeryan** [comment]
@emil-nasso I have not had a chance to work on a format selection implementation yet. I have read back through your comments and I want to point out that the debug options use console.log so you will see all the information by opening `help>Toggle Developer Tools`. I am still curious why you have a format selection option on your context menu. I don't have that but it appears like it tries to use my extension to format. Do you have an extension adding that functionality?
