### ISSUE TITLE
Update links/references to PHPCS repos etc

### ISSUE THREAD

**Issue by jonathanbossenger** [valeryan/vscode-phpsab#118]
PHPCS was [recently abandoned by its original developer](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/109). The project continues in the [PHPCSStandards](https://github.com/PHPCSStandards/PHP_CodeSniffer) organization.

I'm opening this issue so that we can update any links from the old PHPCS repos/package URLs to the new ones.

**Comment by valeryan** [comment]
Thanks, i was thinking we might need to do something along these lines. Although the package name for composer is the same, we want to have any links going to the current information. I think we may also need to look at adding a minimum PHPcs version supported and tool etc...
