### ISSUE TITLE
VS Code 1.42 removed the "formatOnSaveTimeout" setting

### ISSUE THREAD

**Issue by thijsputman** [valeryan/vscode-phpsab#12]
It appears the [January 2020 release of VS Code](https://code.visualstudio.com/updates/v1_42) (1.42) removed the `editor.formatOnSaveTimeout` setting.

Adding the setting manually to `settings.json` still has the below code pick up on it (so there is no immediate issue with current functionality):

https://github.com/valeryan/vscode-phpsab/blob/9834bfae53f24bb9e2728fd3dab4f65b4d68c557/src/configuration.ts#L23

Reading the [change log](https://code.visualstudio.com/updates/v1_42#_handling-slow-save-operations), it appears VS Code is recommending removing the timeout from save operations altogether and simply let them run their course...

**Comment by valeryan** [comment]
Thanks for the heads up! I will check that out.

**Comment by valeryan** [comment]
I just pushed an update that removes this setting. Thanks.
