### ISSUE TITLE
Sniffer doesnt work with associated files.

### ISSUE THREAD

**Issue by SamTyurenkov** [valeryan/vscode-phpsab#125]
```
"files.associations": {
    "*.html": "php"
}
```
When working with php inside .html templates, sniffer doesnt seem to validate or fix errors.

**Comment by jonathanbossenger** [comment]
@valeryan, could I check with you here. Is this a similar issue to https://github.com/valeryan/vscode-phpsab/issues/109. I'm not aware of phpcs working on .html files, but I could be mistaken.

**Comment by valeryan** [comment]
Yes, this is similar to #109 and we are not going to support or add features around deprecated functionality. This extension specifically only activates for php file types when the extension is registered in VSCode.

**Comment by SamTyurenkov** [comment]
@valeryan @jonathanbossenger 

No it is not similar issue.

The difference is - the one you mentioned is about different languages - css or js.
While my issue is about working with php language but inside an .html file.

Please reopen, I dont seem to have access rights.

**Comment by SamTyurenkov** [comment]
Example code:

```template.html
<!-- html file with regular html markup, but with php embeddings.
<div>
Regular html markup
</div>

<?php
//Php code that could be sniffed
$variable = 'hello world';
?>

```

**Comment by SamTyurenkov** [comment]
![image](https://github.com/valeryan/vscode-phpsab/assets/19373777/23587cbb-4665-4136-ab1f-771a514d71cf)

**Comment by valeryan** [comment]
I don't do php anymore but I can imagine why you would want to invert and embed php in html. However, if you tell VSCode to treat the file as php the extension should activate. Phpcs may not that up though. I will look at it but I don't see this working.

**Comment by SamTyurenkov** [comment]
@valeryan in my projects I dont implement such crazy things, but I have to work with code written by others, and unfortunately I met such a case, where I need those .html files to be sniffed as well.

Some template files of an unpopular CMS.

**Comment by jonathanbossenger** [comment]
@SamTyurenkov are you able to run phpcs in the terminal against the .html template files?

I just did a quick test using

```
phpcs -p example-file.html --standard=PSR1
```

Against an .html file which included the following code

```
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>
<?php
class my_class(){
    function my_class(){
        return true;
    }
}
?>

</body>
</html>
```

and none of the expected phpcs errors or warnings were reported.

**Comment by SamTyurenkov** [comment]
@jonathanbossenger im not near PC right now, but didnt think about it.

Actually I keep forgeting that extension cant do more than actual executable can.

If it cant - sorry, probably close this issue then.

**Comment by jonathanbossenger** [comment]
Yup, as far as I know that is the case, so I'll close this out.
