### ISSUE TITLE
Doesn't format

### ISSUE THREAD

**Issue by justlevine** [valeryan/vscode-phpsab#13]
When I save a file, I get a notice that `FIXER: Formatting the document is taking longer than the configured formatOnSaveTimeout. Consider setting it to at least 2 seconds (2000).`

I've set "phpsab.formatOnSaveTimeout": 50000`, but that doesnt change anything, no matter how long I wait.

With debugging on, I get the following error:

```
[2020-02-14 20:47:32.524] [exthost] [error] [valeryanm.vscode-phpsab] provider FAILED
[2020-02-14 20:47:32.524] [exthost] [error] undefined
```
Ideas?

**Comment by valeryan** [comment]
See issue #12. I am currently investigating how vscode will handle timeouts without this setting and will probably have to update some behavior.

**Comment by justlevine** [comment]
Just to clarify it also happens when formatOnSaveTimeout _isn't set_. Got the error which is why I set it.

No need to respond if it's the same issue/root cause.

**Comment by valeryan** [comment]
The setting is removed from vscode so I am not sure what it will return in the code where the extension tries to get that setting from the editor config. Does the document format if you select format document for the context menu and if it does you should see a line like `fixer: 245.545ms` let me know how long its taking.

**Comment by valeryan** [comment]
@justlevine if you feel up to some testing I have pushed up a branch with all the timeout settings removed to see if it resolves or reveals the issue you are having. 

To test this branch:

1. Clone this repo.
1.  Checkout the `no-timeout-settings` branch.
1. Run `npm i` in the cloned directory.
1. Open the repo in vscode.
1. Hit f5 to run the code. This will launch a new instance of vscode with this test extension loaded. 
1. Open your code in the new vscode instance and attempt to fix code using both methods. 
1. Post any errors that show up in the debug console on the original vscode instance.

Alternatively, you can send me a copy of the file that fails to format with any sensitive data removed and I can troubleshoot further. `samrhilson` `@` `gmail.com`

**Comment by valeryan** [comment]
I went ahead and published the new no timeout code. Let me know if it fixes your issue. For now I am closing this until I hear from you. Thanks.

**Comment by jasonwilliams** [comment]
Im getting this again on v0.0.11
Any ideas @valeryan ?

```
[2021-01-20 12:02:37.728] [exthost] [error] [valeryanm.vscode-phpsab] provider FAILED
[2021-01-20 12:02:37.728] [exthost] [error] undefined
[2021-01-20 12:06:28.364] [exthost] [error] [valeryanm.vscode-phpsab] provider FAILED
[2021-01-20 12:06:28.364] [exthost] [error] undefined
```
