### ISSUE TITLE
Fails if Path contains Spaces on Mac

### ISSUE THREAD

**Issue by djstini** [valeryan/vscode-phpsab#136]
Hey,

somehow recently i get the following error when trying to format a file in a path containing a Space: 

```
SyntaxError: Unexpected token 'E', "ERROR: The"... is not valid JSON
["ERROR" - 10:25:58] ERROR: The file "Sites/xxx/app/public/... does not exist.
```

The file i am trying to format is in "/Local Sites/xxx/app/public/..." so i am rather sure that it is a problem passing the space to the formatter.

This used to work before.

Cheers,
Dennis

**Comment by bitojoe** [comment]
Can confirm I'm also experiencing this. Rolled back to the last version for now.

**Comment by phalkmin** [comment]
Yep, same error here

**Comment by zrrmfa** [comment]
same

**Comment by aslamdoctor** [comment]
Same issue.

**Comment by pablofsc** [comment]
Same on Windows. Rolling back to 0.0.18 fixed it.

**Comment by Dekadinious** [comment]
Fails on Windows 10 on & also, and spaces.

**Comment by jonathanbossenger** [comment]
It looks like the [fix](https://github.com/valeryan/vscode-phpsab/pull/129) for #128 has introduced this error because removing `shell: true` from the `spawn` options object resolves this issue.

I will continue investigating.

**Comment by jonathanbossenger** [comment]
I have created #139 to fix this issue. 

I don't have access to a Windows machine at the moment (I'm away from my office for a week), so if anyone can help test the PR in Windows, that would be helpful. Otherwise I can test when I get back.

**Comment by mhmdAmin** [comment]
@jonathanbossenger 
I'm on a Windows machine now and can confirm that the issue still exists

Here is the error:
----------------------
ERROR: The file "Sites\amin\app\public\wp-content\plugins\aminz-elementor-addons\includes\widgets\traits\aminz-buttons-group-trait.php" does not exist.

Run "phpcs --help" for usage information


SyntaxError: Unexpected token 'E', "ERROR: The"... is not valid JSON
-------------
