### ISSUE TITLE
Release 0.0.20

### ISSUE THREAD

**Issue by jonathanbossenger** [valeryan/vscode-phpsab#143]
@valeryan while we discuss/test #141 I'm opening this to check if you're happy if we release 0.0.20, which includes the PRs #139 and #140?

AFAIK i have the relevant permissions to perform the release, but wanted to check with you before I just go ahead.

**Comment by valeryan** [comment]
If you feel confident and comfortable doing it go ahead. The caveats is that the secret key for releasing this is tied to my publisher account and it sometimes expires. I will have to see if I can adjunct you into my publisher account so that you don't get locked out of doing a release of I am not around.

**Comment by jonathanbossenger** [comment]
Ah, in that case maybe it's better if you release, when you have time, of course.

**Comment by valeryan** [comment]
The secret key should be valid right now. I think I renewed it a few months ago.

**Comment by Dekadinious** [comment]
Not to bug anyone, but I am eagerly awaiting this release :D

**Comment by jonathanbossenger** [comment]
@Dekadinious no, the reminder is good. I've been dealing with a lot of work and personal stress since these comments, but I will try and get things going this week. There's also another PR (#145 ) that I need to test, that we should probably include in this release.

**Comment by Dekadinious** [comment]
Is there anything I can do to help in this matter? :)

**Comment by valeryan** [comment]
Yeah, I have been super busy with work. We are releasing new Core D&D books so I have had no time for side stuff. Sorry.

**Comment by jonathanbossenger** [comment]
I had some time this morning, so I have created the next release: https://github.com/valeryan/vscode-phpsab/releases/tag/v.0.0.20

Not sure how long it takes to push everything to the Marketplace. I'll keep an eye on this over the course of the day.

**Comment by jonathanbossenger** [comment]
@valeryan I drafted a new release for v.0.0.0.20 and it seems the workflow failed

https://github.com/valeryan/vscode-phpsab/actions/runs/11839743232

Did I do something wrong?

**Comment by jonathanbossenger** [comment]
I see you are already working on this here https://github.com/valeryan/vscode-phpsab/pull/151

**Comment by jonathanbossenger** [comment]
Thanks @valeryan 

@aslamdoctor can you please test if the new version fixes the spaces issue.

Thanks

**Comment by aslamdoctor** [comment]
@jonathanbossenger yep, its working correctly on all my "Local" projects which has space in the path. 🎉
