### ISSUE TITLE
No problems in the workspace?

### ISSUE THREAD

**Issue by Dekadinious** [valeryan/vscode-phpsab#147]
I am coming from the wongj extension, and there the "Problems" tab in my workspace shows all failed sniffs that did not get automatically fixed. I am just realizing that this does not happen for this extension.

I was just wondering if I am missing something?

**Comment by Dekadinious** [comment]
I would add here that doing phpcs "filename" in the terminal will give errors:

FOUND 4 ERRORS AND 3 WARNINGS AFFECTING 7 LINES
--------------------------------------------------------------------------------
  99 | ERROR   | Inline comments must end in full-stops, exclamation marks, or
     |         | question marks
 212 | ERROR   | Missing doc comment for function [function_name]
 228 | WARNING | print_r() found. Debug code should not normally be used in
     |         | production.
 239 | ERROR   | Empty IF statement detected
 252 | WARNING | print_r() found. Debug code should not normally be used in
     |         | production.
 269 | WARNING | print_r() found. Debug code should not normally be used in
     |         | production.
 345 | ERROR   | Missing doc comment for function [function_name]
--------------------------------------------------------------------------------

Time: 670ms; Memory: 14MB

But none of these are shown under the "problems" tab. Only fatal syntax errors are shown, but it's unclear if they come from this extension or from VSCode itself. Where should I expect to see the errors and warnings from the extension? :)

**Comment by calebsmithdev** [comment]
Also asking for help on this. I don't even see the issues in the problem tab for a single project. I swear I saw errors in both single projects and workspaces before, but I can't forget out what happened or what changed that could have impacted it.

**Comment by calebsmithdev** [comment]
I went back to version 0.0.17 and everything is working now. 0.0.18 did not work either.

**Comment by cstielper** [comment]
Same issue for me, although version 18 worked fine. 

![phpcbf](https://github.com/user-attachments/assets/76339526-4d8d-4b03-872d-39116483da55)

Running "PHPCBF: Fix this file" from the command palette fixes the errors if they exist, they're just not displayed.

**Comment by Dekadinious** [comment]
Version 0.0.20 fixed this again for me. If @calebsmithdev and @cstielper can confirm, I can close the issue.

**Comment by jonathanbossenger** [comment]
Thanks @Dekadinious 

@cstielper can you confirm whether your last test was using the newer [0.0.20](https://github.com/valeryan/vscode-phpsab/releases/tag/v0.0.20) release.

**Comment by cstielper** [comment]
> Thanks @Dekadinious
> 
> @cstielper can you confirm whether your last test was using the newer [0.0.20](https://github.com/valeryan/vscode-phpsab/releases/tag/v0.0.20) release.

@jonathanbossenger 

"Yes," my last test was using the latest release.

**Comment by jonathanbossenger** [comment]
Thanks everyone. Going to close this out then.
