### ISSUE TITLE
PHPCBF appending what appears to be a terminal command to file. 

### ISSUE THREAD

**Issue by justinwhall** [valeryan/vscode-phpsab#17]
As the subject says, after saving a document CBF runs and runs succesfully but the following is appended to the document that is beautified. 

Config:
```
    "phpsab.executablePathCS": "/path/to/phpcs",
    "phpsab.executablePathCBF": "/path/to/phpcbf",
    "phpsab.standard": "phpcs.xml.dist",
    "phpsab.snifferMode": "onType",
    "phpsab.autoConfigSearch": false,
    "phpsab.snifferTypeDelay": 100,
    "phpsab.debug": false,
```

![image](https://user-images.githubusercontent.com/877404/79696382-9bfcbc80-8239-11ea-8946-4e9855420ddc.png)

**Comment by valeryan** [comment]
I am not able to replicate this bug. Perhaps you have some other extension that is breaking the process. Can you try this with php-sab in isolation? Disable all extensions and just enable php-sab.  If that does fix the issue then enable extension until you find the conflicting extension and let me know. I can then see if it can be patched to work with the extension.

**Comment by justinwhall** [comment]
Greeting @valeryan - disable everything. No dice. However, something that may be of interest to you... If I manually run `phpcbf  page.php` the same line is output to the terminal. 

```
➜  start-us-up-now (preprod) ✗ phpcbf page.php
cd /var/www/kauffman/wp-content/themes/start-us-up-now; /var/www/phpcs/[bin(v3)|scripts(v2)]/phpcbf page.php
F 1 / 1 (100%)



PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
page.php                                              1      0
----------------------------------------------------------------------
A TOTAL OF 1 ERROR WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 1.71 secs; Memory: 10MB
```

**Comment by valeryan** [comment]
Well, it sounds like you have an issue with phpcs/phpcbf. My extension uses those tools but I do not maintain them. You should check out the issues at https://github.com/squizlabs/PHP_CodeSniffer and see if anyone else has a similar problem. If you are using a version fo phpcs/phpcbf that is packaged with WordPress it is probably very outdated. You should consider installing the current version of these tools through composer or at a global level and try the extension with that version active.

**Comment by valeryan** [comment]
@justinwhall did you ever get this figured out. I was not able to replicate any similar behavior. I am closing this for now. Feel free to reopen if you have new information.
