### ISSUE TITLE
PHPCBF - Not formatting (command 'fixer.fix' not found)

### ISSUE THREAD

**Issue by mc316** [valeryan/vscode-phpsab#21]
### Error Prompt by VSCode

`Command 'PHPCBF: Fix this file' resulted in an error (command 'fixer.fix' not found)`

### Issue
`PHPCBF` is **_not_** working

### Settings.json (User)

```
    "phpsab.autoConfigSearch": false,
    "phpsab.snifferEnable": true,
    "phpsab.fixerEnable": true,
    "phpsab.standard": "/home/user/.vscode-custom/configurations/Sniffer-PHPCS-Ruleset",
    "phpsab.snifferMode": "onType",
    "phpsab.snifferTypeDelay": 250,
    "phpsab.snifferShowSources": true,
    "phpsab.debug": true,
    "phpsa": true,
    // Since auto config is disabled, empty executable path means to execute global phpcs
    // "phpsab.executablePathCS": "~/.config/composer/vendor/bin/phpcs",
    // "phpsab.executablePathCBF": "/home/user/.config/composer/vendor/bin",
    "phpsab.allowedAutoRulesets": [
        ".phpcs.xml",
        ".phpcs.xml.dist",
        "phpcs.xml",
        "phpcs.xml.dist",
        "phpcs.ruleset.xml",
        "ruleset.xml"
    ],
```

### Setup
I wanted to use global `phpcs` and `phpcbf`, that is why `phpsab.autoConfigSearch` is set to **false**. and left `phpsab.executablePathCS and phpsab.executablePathCBF` empty.

**Comment by valeryan** [comment]
The global handler is not very robust and will only find a global install if phpcs and phpcbf are specifically in the system path. I need to rewrite the global handler to search for any available global instance of phpcs and test if it works. If you want to used a global instance specify it directly in you path.
