### ISSUE TITLE
vscode library is deprecated

### ISSUE THREAD

**Issue by pattisahusiwa** [valeryan/vscode-phpsab#22]
Deprecated `vscode@1.1.37`: This package is deprecated in favor of `@types/vscode` and `vscode-test`. For more information please read: https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest

**Comment by valeryan** [comment]
Thanks, I have updated all the dependencies in my working branch and it will be release soon.
