### ISSUE TITLE
Extension PHP sniffer & beautifier cannot format!

### ISSUE THREAD

**Issue by mdmag** [valeryan/vscode-phpsab#27]
I have this error in my VS : Extension PHP sniffer & beautifier cannot format [PHP_FILE_NAME].php file.
What can be the problem?

**Comment by valeryan** [comment]
Based on the information you have given me I would say I would say phpsab cannot format the file. To provide a more in-depth answer you will need to provide the an outline of your configuration, version of phpcs, maybe an example of the file that does not format if it's possible, some confirmation of the debug output in the developer console, etc

**Comment by mdmag** [comment]
How can I get the debug output?

**Comment by valeryan** [comment]
Make sure debug is set to true under phpsab settings and then got to help> toggle developer tools to get debug output.

**Comment by alexandreserradev** [comment]
Same problem here, phpcbf are not fixing all the errors
PHP 7.3
squizlabs/php_codesniffer: 3.5.5 <- project-wide Installation
Framework: Laravel 6

Before format document
![Before format](https://user-images.githubusercontent.com/38169175/88852693-a0cbf780-d1bc-11ea-8981-1fb2d3eb4973.png)
-
After format document
![Captura de Tela_plasmashell_20200729165305](https://user-images.githubusercontent.com/38169175/88852823-d07aff80-d1bc-11ea-806e-5c8d374b1d24.png)

phpcs.xml
![phpcs](https://user-images.githubusercontent.com/38169175/88852868-e092df00-d1bc-11ea-9a91-2d4a0dd95e0e.png)

Config vscode
![config-vscode](https://user-images.githubusercontent.com/38169175/88852902-ed173780-d1bc-11ea-9be3-9c881886a872.png)

I tested it set phpcbf path, but it didn't work

**Comment by valeryan** [comment]
In your instance, it looks like phpcbf is active and working it just did not fix all the errors. If you run phpcbf against the document on the command line with this same ruleset does it fix those if statements? Depending on if the rule that is erroring their does not implement a fixer it will not change the code. In some instances, you have to look at the rule that is flagging the error and see if that rule has a fixer setup.

**Comment by alexandreserradev** [comment]
@valeryan 
**I changed this:**

`<rule ref="PEAR.ControlStructures.ControlSignature"/>`

**for this:**
```
<rule ref="Squiz.ControlStructures.ControlSignature">
    <properties>
        <property name="requiredSpacesBeforeColon" value="0" />
    </properties>
</rule>
```

And now works well !! Thanks 🙌🏾

**Comment by valeryan** [comment]
@mdmag haven't heard from you in a bit. I guess you solved your issue or moved on. Feel free to reopen if you still need some help.
