### ISSUE TITLE
Problem reporting timing out

### ISSUE THREAD

**Issue by naxvog** [valeryan/vscode-phpsab#29]
Hi there,

first of all thank you for your extension. Love it!

I am having trouble displaying the results of phpcs.

All configuration parameters are successfully parsed and the commands output using the debug mode are reasonable and will produce an output if ran manually.
I started digging in the source and hot-modifying the extension to get some more debug output. It seems the [`done`-Promise](https://github.com/valeryan/vscode-phpsab/blob/b7b93159de0a4691f3c62ca86c537cf921daa0a8/src/sniffer.ts#L279) is killed before it can return anything. Continued diffing a little further and commented out the [`kill`-Timeout](https://github.com/valeryan/vscode-phpsab/blob/b7b93159de0a4691f3c62ca86c537cf921daa0a8/src/sniffer.ts#L337) resolving the problem.

Increasing the timeout to 30s will solve this issue for me as timing `phpcs` itself resulted in about 4.5s of runtime (for ~900 lines of code).

Please increase the timeout to a more reasonable level. Also it would be nice to let us control the timeout via the extension settings.

PS: Upgraded my setup a month ago and sporting a Ryzen 3800X so raw performance should not be the issue here.

**Comment by valeryan** [comment]
@naxvog I will look at this for you but the kill system timer is an if statement to check if a kill event has happened and only triggers if the kill event has been called. If you have a nonsecure example that you can share with me in some way I can test it but I regularly work with much larger files with no issue.

**Comment by naxvog** [comment]
Hey valeryan thanks for answering.
Please correct me if I'm wrong but reading your explanation I realized that I do understand the line in question differently.

For reference [line 337](https://github.com/valeryan/vscode-phpsab/blob/b7b93159de0a4691f3c62ca86c537cf921daa0a8/src/sniffer.ts#L337):
```typescript
setTimeout(() => !sniffer.killed && phpCliKill(sniffer), 3000);
```
Pseudo-Code:
```
Check in 3s from now:
  If the sniffer is not killed:
    kill the sniffer
```

To avoid confusion: I am specifically not asking about the [cancelation request on line 277](https://github.com/valeryan/vscode-phpsab/blob/b7b93159de0a4691f3c62ca86c537cf921daa0a8/src/sniffer.ts#L277)

**Comment by valeryan** [comment]
I will try to take a look this weekend. I will try to remove the need for that kill system by trying to address the bug that this is maskingthe problem of 10 or so phpcs instances getting spun up but never killed when a new empty php file is created and you add a php tag to the top of the document. I locked in what was causing the issue many moons ago but have not yet taken the time to add a proper fix. This will remove the need for attempting to kill hung phpcs processes.

**Comment by valeryan** [comment]
I removed this call and method. I will have to keep an eye out to see if the weird hung phpcs processes start showing up again. If they do I will find a better solution than just scanning for phpcs instances and killing them all. Let me know if the new version fixes your issue.

**Comment by naxvog** [comment]
Version 0.0.11 fixes my issue. Would you like me to look for zombie phpcs processes in a couple of days?

**Comment by valeryan** [comment]
Yes if you do see phpcs processes get hung and high cpu usage please report it. I haven't figured out a way to consistently trigger the bug yet.
