### ISSUE TITLE
Autodetect phpcs from workspace sub-directory where the file belongs

### ISSUE THREAD

**Issue by shivapoudel** [valeryan/vscode-phpsab#30]
Originally reported here previously https://github.com/wongjn/vscode-php-sniffer/issues/31

But this extension is far better so adapt this support!

**Comment by valeryan** [comment]
I am not sure what you are asking. Are you saying you need multiple vendor folders in subdirectories for different versions of phpcs? Or are you asking for the correct XML config to be used? Go-to functionally is not provided by phpcs so I am not sure what that has to do with this either. 

This extension already has multiple workspace support and will autodetect any phpcs XML file in a subfolder and use it.

**Comment by shivapoudel** [comment]
Yes, it detects multiple phpcs XML file in a subfolder and uses it, perfect but I need to supply for a composer JSON file which is not possible for all the sub-directories and is somehow hassle.

Yes I need multiple vendor folders in subdirectories for different versions of phpcs because we do have multiple plugins in WordPress project and is located like this:

```
wp-contents > plugins > example-1-plugin > {composer.json|vendor|phpcs.dist}
wp-contents > plugins > example-3-plugin > {composer.json|vendor|phpcs.xml.dist} - Ruleset is correctly fetched thanks for this.

Since we have to develop and maintain folders of plugins with different architecture in WordPress, fetching respective composer.json and parsing phpcs will be much helpful.
```

**Comment by shivapoudel** [comment]
@valeryan Additionally, do also support [vscode variable references](https://code.visualstudio.com/docs/editor/variables-reference) in `phpsab.composerJsonPath` and other PHPCS and PHPCBF paths. Just like how we can do for integrated terminals cwd https://code.visualstudio.com/docs/editor/integrated-terminal#_using-variables

```"terminal.integrated.cwd": "${workspaceFolder:wordpress-develop}/wp-content/plugins/example-1-plugin"```

I have face this issue in the context of vscode integrated terminal so requesting this phpcs extension to support variable reference. If we have two folders in the workspace one `wordpress-develop` another `wordpress-production` then if the `example-1-plugin` doesn't reside under `wordpress-production` then sometimes terminal display notices folder not found because of multiple folders check. Thus if we provide support variable reference `${workspaceFolder:wordpress-develop}` then it will look that path only on `wordpress-develop` and this will be great.

**Comment by shivapoudel** [comment]
@valeryan Any updates on the autodetect of any `composer.json` file in a subfolder and use it for detecting executable files and installed paths for phpcs?

**Comment by valeryan** [comment]
This is a side project that I update and maintain as I have time. However, if I understand what you are asking, I think there are other ways to accomplish a simpler setup.  

There is really no reason to target different versions of phpcs or phpcbf unless the plugin is referencing a very old ruleset in which case I would not use that very outdated plugin. I would install phpcs/cbf globally, make sure that the rulesets are available on the global install, and then let the autodetect standards handle the per folder configuration of how the global phpcs/cbf runs by detecting .phpcs.xml files. 

Also, I would use a composer plugin such as the [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) to avoid all those nasty duplicate vendor folders. I created an example of what I am talking about. [Wordpress Project Example](https://github.com/valeryan/vscode-phpcs-wp-plugin-example/tree/master). 

But that's just how I would do it.

**Comment by shivapoudel** [comment]
@valeryan Impressive, I will have a look at this architecture and will let you know if this resolves the issue soon 👍

**Comment by shivapoudel** [comment]
@valeryan I tried to replicate the above approach by merging and it solves the issue. But still, if there would be an option to auto search composer.json then it would be very much helpful.

**Comment by shivapoudel** [comment]
@valeryan are you planning any configuration option for auto detecting composer.json just like phpcs config files.

**Comment by valeryan** [comment]
I will work on it at somepoint if it is feasable. Like many people, I have a full time gig and I just hack on stuff like this on the weekends sometimes.

**Comment by valeryan** [comment]
https://github.com/valeryan/vscode-phpsab#maintenance-status

I am not able to support new features.
