### ISSUE TITLE
Only format modified code not the whole file

### ISSUE THREAD

**Issue by shivapoudel** [valeryan/vscode-phpsab#31]
As now VSCode support `editor.formatOnSaveMode` for `modifications`. This extension can also accept it why using that setting, currently, I got an error. I think we and adapt `--filter=gitmodified` CLI args in PHPCS to support this.

**Comment by edysmp** [comment]
It would be be great to add support for this new feature https://code.visualstudio.com/updates/v1_49#_only-format-modified-text
Currenlty it is not working for me too :(

**Comment by valeryan** [comment]
It would be difficult to support the only modified setting provided by vscode but I can add a configuration option to my extension that will include the `--filter=gitmodified` when calling phpcbf.

**Comment by valeryan** [comment]
This should mostly work now in v0.0.14...
