### ISSUE TITLE
Include rule name in PHPCS error message

### ISSUE THREAD

**Issue by coccoinomane** [valeryan/vscode-phpsab#33]
Hello, and thank you for this great extension!
I would like to suggest a small feature request: it would be great to have a `ruleName` field in the error JSON with the name of the rule being broken.

For example, take [this PHPCS error](https://idearia.link/FyjeEq) generated by the `WordPress.ControlStructures.DisallowShortTernaryOperator` rule:

```
{
	"resource": "functions-cpt-professionisti.php",
	"owner": "php",
	"severity": 8,
	"message": "Using short ternaries is not allowed",
	"source": "phpcs",
	"startLineNumber": 1181,
	"startColumn": 47,
	"endLineNumber": 1181,
	"endColumn": 47
}
```

Having an extra field like this

```
"ruleName": "WordPress.ControlStructures.DisallowShortTernaryOperator",
```

would save me a ton of time each time I want to suppress a rule!

**Comment by valeryan** [comment]
Have you tried setting `phpsab.snifferShowSources` to true?

**Comment by coccoinomane** [comment]
Thank you, it worked! I did not know the flag existed, sorry for that.

On a side note (not urgent at all) today I introduced by mistake a non-existing rule in my phpcs.xml.
As expected, the extension stopped working... but it did not show any error message in VS Code.
I can open a separate issue if you want.

Thanks,
Guido

**Comment by valeryan** [comment]
Yes, please add a separate issue for that with details so I can look into it. Thanks.
