### ISSUE TITLE
multi-root workspace handling

### ISSUE THREAD

**Issue by kermage** [valeryan/vscode-phpsab#34]
First of all, thanks for the "better" multi-root workspace support, but is it possible to add a setting that will allow the extension to do what it was actually doing prior to #23? That is, to use the first root folder in the workspace to configure and run both phpcs and phpcbf to all other roots.

Here is a sample workspace when I am doing WordPress projects
```
{
	"folders": [
		{
			"path": ".",
		},
		{
			"path": "wp-content\\themes\\my-theme",
			"name": "My Theme",
		},
		{
			"path": "wp-content\\plugins\\my-plugin",
			"name": "My Plugin",
		},
	],
	"settings": {
		"files.exclude": {
			"my-theme": true,
			"my-plugin": true,
		},
		"phpsab.composerJsonPath": "composer.json",
		"phpsab.standard": "phpcs.xml",
	},
}
```

The first root points to the WordPress install folder which is also the git root of the project, then the 2 more roots are like shortcuts to the theme and plugin folder where I mostly work.

**Comment by valeryan** [comment]
In this instance, I would recommend doing a workspace config and set the correct path the phpcbf and phpcs manually. 

[xkcd: Workflow](https://xkcd.com/1172/)
