### ISSUE TITLE
Does not seem to work with windows

### ISSUE THREAD

**Issue by Madpeterz** [valeryan/vscode-phpsab#36]
Even if you set the plugin "Debug" to enable info to console there does not seem to be any output at all to show its started.

expected:
1: a message that the extension has started.
2: a message if it was able to find phpcs (and where it was loaded from)
3: a message of it was able to find a custom ruleset ie "phpcs.xml" at the top level - or a message stating what default ruleset it is using.
4: a message of any extra rulesets that are loaded (eg SlevomatCodingStandard)
5: a message on save / on type that it has started checking the file
6: problems found to be displayed under the problems area.

Example output:
Extension "PHP Sniffer & Beautifier" Loaded (Version: 0.0.11)
PHPCS found - local project vendor folder
PHPCBF found - global install [windows]
phpcs.xml found in base workspace
- PSR12
- LineLength
- DisallowLongArraySyntax

found SlevomatCodingStandard in local vendor folder
"required by phpcs.xml" 
- TrailingArrayComma
- ReturnTypeHint

Started checking file: example.php
found 2 problems (see tab)

**Comment by valeryan** [comment]
I debug to the developer console and not an output channel. Person preference... However, I was working on a branch to switch over to logging to the output channel so it's easier for others to see the debug information.  You can use `ctrl+shift+i` to open the developer console.
