### ISSUE TITLE
After running PHPCBF it should auto run PHPCS again.

### ISSUE THREAD

**Issue by ggedde** [valeryan/vscode-phpsab#38]
First off, Thanks for this. Works great and love that it is all in one plugin!

After I run the PHPCBF to fix any issues it still shows the issues. I have to then save the file then the issues go away.
Instead I would prefer that PHPCS auto runs after PHPCBF completes.

I know there is a onType option, but I would not prefer that.

Thanks

**Comment by valeryan** [comment]
When the phpcbf runs it modifies the file in memory, not on disk and phpcs runs against the file on disk. That's why you have to save the document yourself. I can look and see if the behavior can be adjusted so that it saves the file but I not sure if it will work.

**Comment by ggedde** [comment]
@valeryan That makes sense. I would prefer not to have it save the file, but maybe others would like that. So it would be best to have that as a setting. I would just prefer that phpcs runs on the file in memory only once after phpcbf runs and completes. After that having phpcs run on the file on disk is fine.

**Comment by valeryan** [comment]
The way phpcs runs in either` on type` or `on save`. I don't really see a way to implement this, so I am closing this issue. Thanks.

**Comment by ggedde** [comment]
@valeryan No worries, but it seems odd that there is no way to trigger phpcs on the file in memory. I guess someone would need to dig into how the `on type` works as that does run on the file in memory. So just need to know how the `on type` works and then just duplicate that process right after phpcbf runs.

I wish i knew how to look into that, but that is beyond my skillset  :(
