### ISSUE TITLE
Allow for an ignore paths setting

### ISSUE THREAD

**Issue by ggedde** [valeryan/vscode-phpsab#39]
One issue I keep getting is occasionally phpcs will sniff files or folders that I don't care about. Ex when working on Wordpress projects I don't need to sniff /wp-admin/* or /wp-includes/*
I know there is a way to set exclude-pattern on specific rulesets, but that would mean I would need to edit the rulesets of which I use from composer and thus don't want to edit those files.

I would recommend adding an Ignore Paths Setting for this to be added. So we can change it per workspace if needed.
You can reference this:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-files-and-folders

Thanks

**Comment by valeryan** [comment]
you can use exclude patterns in you .phpcs.xml or whatever rule you use. 

```
<exclude-pattern>*/tests/*</exclude-pattern>
```

**Comment by ggedde** [comment]
@valeryan Thanks, but I am specifying a coding standard from a composer installation. As far as I can tell the phpcs documentation states that .phpcs.xml will only be used if a Coding Standard is not specified.

Also I tried putting a .phpcs.xml at the root of my project and removing the standard from the settings, but it was not recognized. I restarted vs code and nothing.
I then tried adding the `allowedAutoRulesets` to point to the root .phpcs.xml, but still not working.
Maybe I just don't know how to configure the file properly.

Any hints to what I need to do to get a .phpcs.xml file to be recognized per project?

**Comment by ggedde** [comment]
@valeryan Nevermind I did get it to work, but it seems to only prefer the .phpcs.xml over the standards setting in phpsab.
So yeah, you can only use one and not both. I had to make sure the standard was not added in the settings and then make sure to restart vscode.

While this does work it does mean that I need to know how to write and configure the .phpcs.xml file. Which is fine, but I kind of liked just putting in "WordPress" in the standard and then just having a ignore setting. Instead of having to manage the .phpcs.xml file.  However, I think that is just a preference and so you can probably close this Issue, but I would still recommend for other users that and ignore setting would be nice.

Thanks

**Comment by valeryan** [comment]
The whole point of this extension really is using .phpcs.xml files to have folder level control of standards. You can specify the ruleset names to search for and allow auto search to find the most appropriate .phpcs.xml ruleset based on the folder that a file is in. It searches up from the file. You can just specify a ruleset in the phpcs.xml file and a set of folders to exclude. 

example .phpcs.xml
```
<?xml version="1.0"?>
<ruleset name="My Wordpress">
    <rule ref="wordpress" />
    <file>.</file>
    <arg name="encoding" value="utf8"/>
    <arg name="extensions" value="php"/>
    <exclude-pattern>*/vendor/*</exclude-pattern>
    <exclude-pattern>*/builds/*</exclude-pattern>
</ruleset>
```

**Comment by ggedde** [comment]
@valeryan Thanks I will have to look into the <rule ref="*" />

**Comment by szaveri** [comment]
@valeryan I think this can be taken care of using #42 where users can add additional parameters such as the one listed above.

**Comment by valeryan** [comment]
I need to add this to the documentation someday so that people will not think it will work but when you call phpcbf on a file directly as this extension does it will override the ignore flag. The author of phpcs has confirmed that it does not make sense to use the ignore flag when you are providing a specific file to fix in your arguments. However it does honor the exclude directive in a ruleset.
