### ISSUE TITLE
phpcs doesn't show warnings

### ISSUE THREAD

**Issue by rahulv3a** [valeryan/vscode-phpsab#46]
It seems like phpcs shows only errors by default, not warnings.

We need to add the `--severity=5` or  `--warning-severity=5` flag in to show the warnings. If you don't want to enable them, by default, you could add an option to do so.

Merging #43 would also help.

**Comment by valeryan** [comment]
I merge #43 so maybe it gives you what you want.

**Comment by rahulv3a** [comment]
Thank you 🙂
