### ISSUE TITLE
Workspace with multi-folders problems.

### ISSUE THREAD

**Issue by 9brada6** [valeryan/vscode-phpsab#5]
Hi... i have the same error as #1.

```stack trace: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''	at normalizeSpawnArguments (child_process.js:407:11)	at Object.spawn (child_process.js:537:38)	at Sniffer.<anonymous> (W:\Programs\vscode\data\extensions\valeryanm.vscode-phpsab-0.0.3\out\sniffer.js:175:45)	at Generator.next (<anonymous>)	at fulfilled (W:\Programs\vscode\data\extensions\valeryanm.vscode-phpsab-0.0.3\out\sniffer.js:9:58)```

the problem is if that I have multiple folders in the workspace, the plugin will not work. I don't know why exactly, I just think that this is because it cannot find the phpcs executable(the composer/vendor folder is not in root directory, It's in another workspace folder, and it seems it will search only the root folder). However, If I put the path to phpcs manually, it will work. 

How I think it should be
1. Is that the extension will search for composer.json or vendor from the file down the bottom, and when it finds, it will load. I know that is too hard.

2. Or the extension will search in all the workspace folders for vendor\bin\phpcs(and remembering them), and when a file needs to be parsed, it will search in all the folder parents and load the first encountered workspace folder that has installed phpcs
---------------------------------------------
Second thing I want say is that in Windows I need to append ".bat" when I write the path to work, It will be cool if the extension could detect and add it when on Windows enviroment. Or just to write the path where phpcs will be found, and extension search for phpcs inside the folder(Like when you write PATH in environment variable).

Thanks.

**Comment by valeryan** [comment]
I have never used a multi-folder project this way because it is not the way I develop. I am typically either working with Laravel or MediaWiki and all development is contained within the single root. I will have to look into this feature but it may take some time to get this working. 

To your second point, the auto search feature will append .bat as needed but if you override it with a path it does not do any processing on your input. It is a manual override and the setting is taken as the source of truth for what you want to use. It would be simple to add auto appending the .bat on windows but I don't like to idea of modifying user input for a manual override setting.

**Comment by valeryan** [comment]
I followed the steps here: https://code.visualstudio.com/docs/editor/multi-root-workspaces
I added two root folders that each had its own composer.json file and did composer install in each folder. This is my test bed: https://github.com/valeryan/multi-root-example

Can you confirm that this would be a good example to represent your setup before I begin testing to make this work?

**Comment by 9brada6** [comment]
Hi... yes... I have composer installed only on one folder, and it's not on the non-root one. If I switch the folders between (the composer becomes the root one), your plugin will work. I think it should be also tested, like if you have composer installed only on a folder(non-root one), if you can... 

I use this setup for WordPress.... In the root folder I have the WordPress, and in another folder a shortcut to a theme folder(I work only on this folder, and I need to include the wordpress root for intellisense/phan function detection). I say shortcut because i can navigate there from the root folder(So the root folder is actually a parent of the second folder, they are not away). And all the composer packages/phpcs/node/... etc is installed under my second folder. I hope you understand what I mean...

Thank you for your time... I think that if you make to work for your example, it will also work for mine....

**Comment by valeryan** [comment]
@9brada6 I have looked into this and I am pretty sure I can fix it to work well but it will be a little bit before I can devote time to reworking it. I envision just taking the tree of settings that hold the discovered information and having it be contained in a root array with an entry for each workspace. With your setup the multi workspace with one not having composer I would expect code linting and fixing to be disabled in that workspace and the extension to be active for the other workspace. That is in line with the current behavior in a single workspace with no composer setup. does that make sense to you?

**Comment by 9brada6** [comment]
Hi... yes, that makes perfect sense to me. If you can disable the linting for the folders below the ones that have composer will be perfect.

**Comment by valeryan** [comment]
@9brada6 I merged in a change that addresses one part of the mulit workspace setup but I will have to do a bit more work to be fully able to support multi workspaces.
