### ISSUE TITLE
PHP Fixer Deletes Contents of File

### ISSUE THREAD

**Issue by nbordeau** [valeryan/vscode-phpsab#6]
VSCode: 1.37.1
PHPSAB: 0.0.3

```
{
"phpsab.snifferShowSources": true,
"phpsab.standard": ".phpcs.xml",
"editor.formatOnSaveTimeout": 2000,
"phpsab.snifferMode": "onType",
"phpsab.autoConfigSearch": false,
}
```

Sometimes when I "fix" the PHP file in question PHPSAB just deletes all of the contents. It usually happens when there is no .phpcs.xml file, but seems to be happening on a few projects when there is one present.

I tried reinstalling the composer project as well as recreating the .phpcs.xml file.

**Comment by valeryan** [comment]
Thanks for the report. I am aware that it can happen but I haven't figured out what actually causes it yet as it is very intermittent. Usually restarting vscode will clear up the issue for me. I think it has something to do with the error checking not catching some situation in which it should not replace the code. It happens most often on windows. What OS are you using?

**Comment by nbordeau** [comment]
Windows (begrudgingly). It seems like it happens when the file can not be found that I specify as the standard. For example, if I set this rule:

```
"phpsab.standard": ".phpcs.xml"
```

and then don't include the .phpcs.xml file.

**Comment by valeryan** [comment]
Okay, that at least gives me a clue of how to try and reproduce this. I generally use the autoconfigSearch and don't specify a standard. I will do a Virtual Box troubleshooting and see if I can track this down. Troubleshooting windows problems can be such a pain.

Thanks.

**Comment by nbordeau** [comment]
Agreed, windows is a pain. I just turned that setting on and changed the default to PSR2. When I start editing our WordPress stuff that has a .phpcs.xml file, I'll let you know if it still is happening.

**Comment by nbordeau** [comment]
So after some more use, it appears that it is only happening when I open up one of our projects and add the .phpcs.xml file to. If I start a new project, everything works as expected. Would it be helpful to send over the code that is causing the issue?

**Comment by nbordeau** [comment]
Okay, here's another scenario that might help:
```
Version: 1.38.0 (system setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Settings:
```
"phpsab.snifferShowSources": true,
"phpsab.standard": "PSR2",
"editor.formatOnSaveTimeout": 3500,
"phpsab.snifferMode": "onType",
```
![Annotation 2019-09-09 095148](https://user-images.githubusercontent.com/52969633/64536708-8dcfe080-d2e7-11e9-950b-f14b81ed3260.png)

File contents:

```
<?php

$productSkus = [
/** 
 * Array of 3000 skus in this style
 * "ABC123",
 */
];
```
On save, the entire file gets deleted.

**Comment by valeryan** [comment]
Thanks for the help tracking this down. I will hopefully have some time this weekend to try and recreate this and get it sorted.

**Comment by valeryan** [comment]
@nbordeau I have not had any problems with phpcbf deleting code with the current changes. I am closing this for now but feel free to reopen it if you experience anything contrary.

**Comment by nbordeau** [comment]
Thanks! I haven't had a chance to try it out but I did install PHPCBF globally instead of per-project via composer and that seemed to solve the problem as well.
