### ISSUE TITLE
Add an option "false" to "phpsab.snifferMode" 

### ISSUE THREAD

**Issue by jjasoncool** [valeryan/vscode-phpsab#63]
Sometimes I want to check sniffer message after finishing the code.
Can add an option that don't check `phpcs` every time when I save the file before I finish the code?

Thank you.

**Comment by valeryan** [comment]
https://github.com/valeryan/vscode-phpsab#maintenance-status

But your request doesn't make any sense to me. Use on save and ignore the errors tell you are ready to look at them....
