### ISSUE TITLE
Using phpcs.xml ruleset in phpsab.standard produces an error

### ISSUE THREAD

**Issue by MannyAdumbire** [valeryan/vscode-phpsab#64]
I'm one step away from configuring this neat extension to work with current development setup.
It works well if installed standards are mentioned by name, but  but am getting below error when trying to use a phpcs config file as the standard:
i.e.    `"phpsab.standard": "./phpcs.xml"` in VSCode settings.json

**ERROR: the "./phpcs.xml" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR12, .....**

I also tried using predefined variables like `"phpsab.standard": "${workspaceFolder}/phpcs.xml"` but that produces the same error.
Is this known issue or am I doing something wrong?

Thanks for any assistance!

**Comment by valeryan** [comment]
Duplicates #65
