### ISSUE TITLE
Exclude pattern with a `relative` option in the configuration file is not respected by the extension

### ISSUE THREAD

**Issue by kanlukasz** [valeryan/vscode-phpsab#67]
### Issue describe:
In my `.phpcs.xml` I use `<exclude-pattern>` using negative `regex`. For this to work, I have to use `type="relative"`.
Thanks to this, I am able to exclude the entire project except specific folders.
_(This is very useful especially when you are working with a strange project structure like e.g. Wordpress)_

When I run `PHP Code Sniffer` from the command line, all my files are interpreted correctly - I mean my exclusions works fine 👍
When I open a file in VSCode - the exclusions don't work 👎 

After a quick test, I noticed that the problem is due to using the `relative` option in configuration

### To illustrate the problem, I am attaching a GIF video below:
![phpcs-rel2](https://user-images.githubusercontent.com/30685349/145361076-1bcef328-49e6-42fe-a4d5-11242fa8756f.gif)

### My `.phpcs.xml` file:
```
<?xml version="1.0"?>
<ruleset name="xxxxxxx">
    <exclude-pattern type="relative">^(?!wp-content/plugins/xxxxxxxxx|wp-content/themes/xxxxxxxxx).+</exclude-pattern>
    <exclude-pattern type="relative">^(wp-content/themes/xxxxxxxx/inc/*.*)</exclude-pattern>
    <exclude-pattern type="relative">^(?!.*.php).+</exclude-pattern>
    <rule ref="WordPress">
        <exclude name="WordPress.WhiteSpace.ControlStructureSpacing"/>
        <exclude name="WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter"/>
        <exclude name="Generic.Arrays.DisallowShortArraySyntax"/>
        <exclude name="Squiz.Commenting.FileComment.Missing"/>
        <exclude name="Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace"/>
        <exclude name="Generic.WhiteSpace.ArbitraryParenthesesSpacing.SpaceAfterOpen"/>
        <exclude name="Generic.WhiteSpace.ArbitraryParenthesesSpacing.SpaceBeforeClose"/>
        <exclude name="WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceAfterArrayOpener"/>
        <exclude name="WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceBeforeArrayCloser"/>
    </rule>
    <rule ref="PEAR.Functions.FunctionCallSignature">
		<properties>
			<property name="requiredSpacesAfterOpen" value="0"/>
			<property name="requiredSpacesBeforeClose" value="0"/>
		</properties>
	</rule>
</ruleset>

```

### Work environment:
- Ubuntu 20.04 focal running on WSL2
- PHP 8
- VsCode version: 1.62.3 (system setup)

### Extension settings that I changed (the rest have default settings):
```
    "phpsab.fixerEnable": false,
    "phpsab.snifferShowSources": true,
```

**Comment by kanlukasz** [comment]
There is an option that my regex was not 100% correct.

Correction:
```
<exclude-pattern>^(?!.*\/wp-content\/plugins\/xxxxxxxxx|.*\/wp-content\/themes\/xxxxxxxxx).*</exclude-pattern>
<exclude-pattern>^(.*\/wp-content\/themes\/xxxxxxxxx\/inc)</exclude-pattern>
<exclude-pattern>.*\.(?!(php$))</exclude-pattern>
```
If the problem recurs, I will reopen this issue
Sorry for the confusion

**Comment by furai** [comment]
I'm not sure if this is actually the same issue but I've noticed that if you have "file" setting then exclude-patterns don't work. When I run phpcs from command line excluded files are correctly identified but when using the extension it will pick up all php files. Like it didn't try to include just the files but everything besides that.
