### ISSUE TITLE
MacOS: phpsab picking up wrong version of PHP for Composer platform check

### ISSUE THREAD

**Issue by andronocean** [valeryan/vscode-phpsab#68]
I'm getting the following error pop up in VS Code on almost every file save:

```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.29. in /(...path/to/project...)/site/vendor/composer/platform_check.php on line 24
```
I'm running macOS Catalina, for which the system PHP is 7.3.29. I have PHP 7.4.27 installed via Homebrew, on my $PATH, and hooked into VS Code as tightly as I could manage. Various checks and settings:

- `php -v` returns `PHP 7.4.27`
- `composer diagnose` shows `PHP version: 7.4.27` and `PHP binary path: /usr/local/Cellar/php@7.4/7.4.27/bin/php`
- In my Code user settings, I have defined `"php.validate.executablePath": "/usr/local/opt/php@7.4/bin/php"`, which Homebrew has symlinked to the binary above.
- my composer.json includes: 
```
    "platform": {
      "php": "7.4"
    }
```
- composer.json _is_ in a subdirectory `site/`, but in my workspace `.vscode/settings.json` I have these defined:
```
  "phpsab.composerJsonPath": "site/composer.json",
  "phpsab.executablePathCS": "site/vendor/bin/phpcs",
  "phpsab.executablePathCBF": "site/vendor/bin/phpcbf",
```
Have I missed something, or is this a bug?

**Comment by andronocean** [comment]
I finally got it working properly, and it looks like my own config was to blame. My zsh setup adds the correct PHP to $PATH in `.zshrc`. For some reason, VS Code didn't seem to pick it up. I added the PHP $PATH rule to `.zprofile` as well, and _after a restart_ the error disappeared. Hasn't shown up again.

**Comment by fishtankStu** [comment]
Please share the file(s) you used to fix this error. Thanks.
