### ISSUE TITLE
How to properly format [PHP 8.1] Enum files

### ISSUE THREAD

**Issue by tcampbPPU** [valeryan/vscode-phpsab#69]
With PHP 8.1 we now have access to Enum 🥳. However I am having a little issue with formatting these files, using this extension in VS Code.

Here is example of my settings `.vscode/settings.json`
```json
{
    "[php]": {
        "editor.defaultFormatter": "valeryanm.vscode-phpsab",
        "editor.formatOnSave": true
    },
    "phpsab.snifferEnable": true,
    "phpsab.executablePathCBF": "./vendor/bin/phpcbf",
    "phpsab.executablePathCS": "./vendor/bin/phpcs",
    "phpsab.snifferShowSources": true,
    "phpsab.snifferMode": "onType"
}
```

And when I format on save here is my ending result
![image](https://user-images.githubusercontent.com/25044744/157965984-f3a17c54-1248-4f04-aceb-bdb6811603dc.png)

If I use somthing else like PHP Intelephense to format, I end up with PHPCS warning.
![image](https://user-images.githubusercontent.com/25044744/157966150-1f9ab8c9-7ce3-4c26-8004-c2ed40eae06f.png)

Any suggestion on anything on my end I need to do to fix?

**Comment by valeryan** [comment]
First, you should only use one formatter to avoid conflicts. The extension itself is a wrapper for easy configuration of phpcs and phpcbf. I don't control the behavior of those scripts. If phpcbf is applying your rules set wrong you would need to file an issue with the phpcs team.

**Comment by tcampbPPU** [comment]
I actually don't use this extension anymore, so I will close
