### ISSUE TITLE
Deprecated: auto_detect_line_endings is deprecated

### ISSUE THREAD

**Issue by avivais** [valeryan/vscode-phpsab#71]
This error seems to be preventing the linter from running properly

macOS Monterey 12.3.1 Macbook pro with Apple Silicon
PHP: 8.1.5
VSC: 1.66.2
PHPSAB: 0.0.15

<img width="848" alt="Screen Shot 2022-05-01 at 15 31 16" src="https://user-images.githubusercontent.com/1503623/166146057-a20ba0bd-db71-4750-93f0-64e547d12bb7.png">

**Comment by spaceo** [comment]
@avivais What was the fix for this? I have the same issue.
