### ISSUE TITLE
Support Docker Compose environments?

### ISSUE THREAD

**Issue by ultimike** [valeryan/vscode-phpsab#88]
I have all my environments in docker machines, and I'd like to configure `phpsab.executablePathCS and `phpsab.executablePathCBF` to run in the container. Something like 

```docker-compose exec php vendor/bin/phpcs path/to/files/to/lint```

I'd rather not run phpcs from my host operating systems.

I was hoping to do something like [this](https://github.com/ikappas/vscode-phpcs/issues/173#issuecomment-1289000156), but I cannot get it working. Is this possible?

-mike

**Comment by mreduar** [comment]
Any update?

**Comment by shaneparsons** [comment]
Yeah, this would be great to have!

[SanderRonde/phpstan-vscode](https://github.com/SanderRonde/phpstan-vscode) has a great implementation of this with their `phpstan.binCommand` config option. Would be great to have something similar here.

**Comment by shaneparsons** [comment]
This fork of this repo appears to work well actually https://github.com/mtbdata711/vscode-phpsab-docker. Probably just a matter of somebody opening a pull request to merge the changes into here.

**Comment by valeryan** [comment]
Yeah, I don't have time to actively work on this project these days and I work in .net now. I will always field PRs though.

**Comment by jonathanbossenger** [comment]
@valeryan perhaps it would make sense to update the readme to include details on the fork that works with docker, and then you could close this ticket?

Happy to submit a pr to update the readme.

**Comment by valeryan** [comment]
Information about how to find the docker fork was added to the readme. Closing this. If the developer of that fork wants to look at a way to add docker support to the main extension through PR I will check it out.
