### ISSUE TITLE
PHP 8.2 Deprecated: Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by acc0re** [valeryan/vscode-phpsab#89]
I get this Error when i´m saving.

Deprecated: Creation of dynamic property SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff::$newlinesCountAfterDeclare is deprecated

**Comment by valeryan** [comment]
That sounds like more of an issue with the coding standard you are using. I would look at whatever SlevomatCodingStandard is.
